version: '3.1'

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules

  backend_node_mongo:
    build:
      context: ./backend_node_mongo
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017

  backend_python_mysql:
    build:
      context: ./backend_python_mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend_python_mysql:/server
    ports:
      - "8001:8001"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8001 
    depends_on:
      - db
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8001

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db



volumes:
  mongodb_data: