name: Build, Test and Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install Dependencies and Run Tests
        run: |
          npm ci
          npm test

      - name: Build and Start the Docker Compose Stack
        run: docker-compose up -d

      - name: Run API Tests
        run: |
          cd server
          npm ci
          npm test

      - name: Run End-to-End Tests with Cypress
        uses: cypress-io/github-action@v6

      - name: Stop the Docker Compose Stack
        run: docker-compose down

      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Build Documentation and App
        run: |
          npm run jsdoc
          npm run build --if-present
       # Set up and test Docker containers (Node.js and MongoDB)
      - name: Docker compose up
        run: |
          docker-compose up -d
          sleep 10
          docker ps
      - name: Cypress tests
        run: |
          cd ./app
          npm run cypress-spec
      - name: Docker compose down
        run: |
          docker-compose down
